name: Publish Package
on:
  release:
    types: [published]
  pull_request: 
    branches: 
      - main
jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sekai-labs'
      - name: Build Package
        run: yarn
      - name: Publish Package
        run: yarn publish::framework
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
